import { Resend } from 'resend';
import supabase from './db-client.js';

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const healthStatus = {
    status: 'healthy',
    timestamp: new Date().toISOString(),
    services: {
      supabase: 'unknown',
      resend: process.env.RESEND_API_KEY ? 'configured' : 'missing',
      googleSheets: process.env.GOOGLE_APPS_SCRIPT_URL ? 'configured' : 'missing',
    },
    website: {
      homepage: 'unknown',
      services: 'unknown',
      servers: 'unknown',
      contact: 'unknown'
    },
    bookingAPI: 'unknown'
  };

  let hasError = false;
  let errorDetails = [];

  // 1. Check Supabase Connectivity
  try {
    if (!supabase) {
      throw new Error('Supabase client is not initialized.');
    }
    const { data, error } = await supabase.from('bookings').select('id').limit(1);
    if (error) throw error;
    healthStatus.services.supabase = 'connected';
  } catch (error) {
    hasError = true;
    healthStatus.services.supabase = 'failed';
    errorDetails.push(`Supabase Error: ${error.message}`);
  }

  // 2. Check Website Pages
  const baseUrl = process.env.WEBSITE_URL || 'http://localhost:5173'; // Fallback to localhost for dev
  const pagesToTest = [
    { key: 'homepage', path: '/' },
    { key: 'services', path: '/services' },
    { key: 'servers', path: '/servers' },
    { key: 'contact', path: '/contact' }
  ];

  for (const page of pagesToTest) {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 5000);
      const response = await fetch(`${baseUrl}${page.path}`, { signal: controller.signal });
      clearTimeout(timeout);
      
      if (response.ok) {
        healthStatus.website[page.key] = 'ok';
      } else {
        throw new Error(`HTTP ${response.status}`);
      }
    } catch (err) {
      hasError = true;
      healthStatus.website[page.key] = 'failed';
      errorDetails.push(`Website Page Load Error (${page.path}): ${err.message}`);
    }
  }

  // 3. Check Booking API (Slot Availability)
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000);
    const apiRes = await fetch(`${baseUrl}/api/bookings`, { signal: controller.signal });
    clearTimeout(timeout);

    if (apiRes.ok) {
      const data = await apiRes.json();
      if (data.success && Array.isArray(data.bookedSlots)) {
        healthStatus.bookingAPI = 'ok';
      } else {
        throw new Error('Invalid JSON response format from booking API');
      }
    } else {
      throw new Error(`HTTP ${apiRes.status}`);
    }
  } catch (err) {
    hasError = true;
    healthStatus.bookingAPI = 'failed';
    errorDetails.push(`Booking API Error: ${err.message}`);
  }

  if (hasError) {
    healthStatus.status = 'degraded';
    console.error('[Health Check] Failures detected:', errorDetails);
  } else {
    console.log('[Health Check] System Healthy');
  }

  // 4. If degraded, send an admin alert
  if (hasError && resend) {
    const internalEmail = process.env.INTERNAL_SALES_EMAIL || 'hello@kktechsolutions.in';
    const fromEmail = process.env.FROM_EMAIL || 'onboarding@resend.dev';
    
    try {
      await resend.emails.send({
        from: `System Alerts <${fromEmail}>`,
        to: internalEmail,
        subject: `🚨 [KK TECH ALERT] System Health Check Failed`,
        html: `
          <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #dc2626;">System Health Check Failed</h2>
            <p>The daily automated health check detected a failure in one of the backend subsystems.</p>
            <h3>Error Details:</h3>
            <ul>
              ${errorDetails.map(err => `<li>${err}</li>`).join('')}
            </ul>
            <p>Please investigate immediately to ensure consultation bookings are not disrupted.</p>
            <hr />
            <p style="font-size: 12px; color: #666;">Generated by KK Tech Solutions Automated Monitoring</p>
          </div>
        `
      });
      console.log('[Health Check] Admin alert email dispatched.');
    } catch (emailError) {
      console.error('[Health Check] Failed to send admin alert:', emailError);
    }
  }

  const statusCode = hasError ? 503 : 200;
  return res.status(statusCode).json(healthStatus);
}
