import { Resend } from 'resend';
import supabase from './db-client.js';

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const healthStatus = {
    status: 'healthy',
    timestamp: new Date().toISOString(),
    services: {
      supabase: 'unknown',
      resend: process.env.RESEND_API_KEY ? 'configured' : 'missing',
      googleSheets: process.env.GOOGLE_APPS_SCRIPT_URL ? 'configured' : 'missing',
    }
  };

  let hasError = false;
  let errorDetails = [];

  // Check Supabase Connectivity
  try {
    if (!supabase) {
      throw new Error('Supabase client is not initialized.');
    }
    const { data, error } = await supabase.from('bookings').select('id').limit(1);
    if (error) throw error;
    healthStatus.services.supabase = 'connected';
  } catch (error) {
    hasError = true;
    healthStatus.status = 'degraded';
    healthStatus.services.supabase = 'failed';
    errorDetails.push(`Supabase Error: ${error.message}`);
    console.error('[Health Check] Supabase failure:', error);
  }

  // If degraded, send an admin alert
  if (hasError && resend) {
    const internalEmail = process.env.INTERNAL_SALES_EMAIL || 'hello@kktechsolutions.in';
    const fromEmail = process.env.FROM_EMAIL || 'onboarding@resend.dev';
    
    try {
      await resend.emails.send({
        from: `System Alerts <${fromEmail}>`,
        to: internalEmail,
        subject: `🚨 [CRITICAL ALERT] KK Tech Solutions Health Check Failed`,
        html: `
          <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #dc2626;">System Health Check Failed</h2>
            <p>The daily automated health check detected a failure in one of the backend subsystems.</p>
            <h3>Error Details:</h3>
            <ul>
              ${errorDetails.map(err => `<li>${err}</li>`).join('')}
            </ul>
            <p>Please investigate immediately to ensure consultation bookings are not disrupted.</p>
            <hr />
            <p style="font-size: 12px; color: #666;">Generated by KK Tech Solutions Automated Monitoring</p>
          </div>
        `
      });
      console.log('[Health Check] Admin alert email dispatched.');
    } catch (emailError) {
      console.error('[Health Check] Failed to send admin alert:', emailError);
    }
  }

  const statusCode = hasError ? 503 : 200;
  return res.status(statusCode).json(healthStatus);
}
